#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHAPTER1_SRC="${CHAPTER1_SRC:-}"
CHAPTER2_SRC="${CHAPTER2_SRC:-}"
CHAPTER3_SRC="${CHAPTER3_SRC:-}"

require_path() {
  if [[ ! -e "$1" ]]; then
    echo "Missing required path: $1" >&2
    exit 1
  fi
}

require_var() {
  local name="$1"
  local value="$2"
  if [[ -z "$value" ]]; then
    echo "Missing required environment variable: $name" >&2
    echo "Set it before running this script, for example:" >&2
    echo "  CHAPTER1_SRC=/path/to/ch1 CHAPTER2_SRC=/path/to/ch2 CHAPTER3_SRC=/path/to/ch3 ./scripts/import_chapters.sh" >&2
    exit 1
  fi
}

copy_file() {
  local src_root="$1"
  local rel_path="$2"
  local dest_root="$3"

  require_path "$src_root/$rel_path"
  mkdir -p "$(dirname "$dest_root/$rel_path")"
  cp "$src_root/$rel_path" "$dest_root/$rel_path"
}

copy_file_list() {
  local src_root="$1"
  local dest_root="$2"
  shift 2

  local rel_path
  for rel_path in "$@"; do
    copy_file "$src_root" "$rel_path" "$dest_root"
  done
}

rsync_clean() {
  rsync -a --delete \
    --delete-excluded \
    --exclude='.DS_Store' \
    --exclude='*.aux' \
    --exclude='*.blg' \
    --exclude='*.log' \
    --exclude='*.out' \
    --exclude='*.pdf' \
    --exclude='*.run.xml' \
    --exclude='*.txt' \
    --exclude='*-blx.bib' \
    --exclude='README.md' \
    --exclude='auto/' \
    "$@"
}

merge_bib_files() {
  perl -0ne '
    BEGIN {
      print "% Auto-generated by scripts/import_chapters.sh\n";
      print "% Re-run this script after updating any chapter repository.\n\n";
    }

    while (/^@.*?(?=^@|\z)/msg) {
      my $entry = $&;
      $entry =~ s/\s+\z/\n/s;

      if ($entry =~ /^\@preamble\b/is) {
        next if $seen_preamble{$entry}++;
        print $entry, "\n";
        next;
      }

      my ($key) = $entry =~ /^\@\w+\s*\{\s*([^,]+)\s*,/s;
      next unless defined $key;
      next if $seen_key{$key}++;
      print $entry, "\n";
    }
  ' "$@"
}

require_var "CHAPTER1_SRC" "$CHAPTER1_SRC"
require_var "CHAPTER2_SRC" "$CHAPTER2_SRC"
require_var "CHAPTER3_SRC" "$CHAPTER3_SRC"

require_path "$CHAPTER1_SRC/Chp1.tex"
require_path "$CHAPTER1_SRC/Chp1.bib"
require_path "$CHAPTER2_SRC/Paper/Chp2.tex"
require_path "$CHAPTER2_SRC/Paper/Chp2.bib"
require_path "$CHAPTER3_SRC/Chp3.tex"
require_path "$CHAPTER3_SRC/References.bib"

rm -rf "$ROOT_DIR/chapters/chapter1" "$ROOT_DIR/chapters/chapter2" "$ROOT_DIR/chapters/chapter3"

mkdir -p \
  "$ROOT_DIR/chapters/chapter1" \
  "$ROOT_DIR/chapters/chapter2/Paper" \
  "$ROOT_DIR/chapters/chapter2/Code/Analysis" \
  "$ROOT_DIR/chapters/chapter2/Code/Descriptive" \
  "$ROOT_DIR/chapters/chapter2/Code/Regressions" \
  "$ROOT_DIR/chapters/chapter3/Subfiles"

copy_file_list "$CHAPTER1_SRC" "$ROOT_DIR/chapters/chapter1" \
  "Subfiles/abstract.tex" \
  "Subfiles/intro.tex" \
  "Subfiles/litrev.tex" \
  "Subfiles/model.tex" \
  "Subfiles/results.tex" \
  "Subfiles/taxation.tex" \
  "Subfiles/mechanism.tex" \
  "Subfiles/lognormal_ret.tex" \
  "Subfiles/conclusion.tex"

copy_file_list "$CHAPTER2_SRC" "$ROOT_DIR/chapters/chapter2" \
  "Paper/Subfiles/abstract.tex" \
  "Paper/Subfiles/introduction.tex" \
  "Paper/Subfiles/litrev.tex" \
  "Paper/Subfiles/data.tex" \
  "Paper/Subfiles/results.tex" \
  "Paper/Subfiles/extensions.tex" \
  "Paper/Subfiles/conclusion.tex" \
  "Paper/Subfiles/appendix.tex"

copy_file_list "$CHAPTER3_SRC" "$ROOT_DIR/chapters/chapter3" \
  "Subfiles/Abstract-chapter3.tex" \
  "Subfiles/Intro-decory.tex" \
  "Subfiles/Motiv-decory.tex" \
  "Subfiles/ExtendedModel-decory.tex" \
  "Subfiles/SWFapproach-decory.tex" \
  "Subfiles/Alternativemeasure-decory.tex" \
  "Subfiles/Computing-decory.tex" \
  "Subfiles/Conclusion-decory.tex" \
  "Subfiles/Appendix-decory.tex"

# Chapter 3 pipeline writes PNGs/CSVs alongside TeX figures and tables; keep them in sync with the fork.
require_path "$CHAPTER3_SRC/Figures"
require_path "$CHAPTER3_SRC/Tables"
rsync -a --delete --exclude='.DS_Store' \
  "$CHAPTER3_SRC/Figures/" "$ROOT_DIR/chapters/chapter3/Figures/"
rsync -a --delete --exclude='.DS_Store' \
  "$CHAPTER3_SRC/Tables/" "$ROOT_DIR/chapters/chapter3/Tables/"

rsync_clean "$CHAPTER1_SRC/Figures/" "$ROOT_DIR/chapters/chapter1/Figures/"
rsync_clean "$CHAPTER1_SRC/Tables/" "$ROOT_DIR/chapters/chapter1/Tables/"

rsync_clean "$CHAPTER2_SRC/Code/Analysis/Figures/" "$ROOT_DIR/chapters/chapter2/Code/Analysis/Figures/"
rsync_clean "$CHAPTER2_SRC/Code/Analysis/Tables/" "$ROOT_DIR/chapters/chapter2/Code/Analysis/Tables/"
rsync_clean "$CHAPTER2_SRC/Code/Descriptive/Figures/" "$ROOT_DIR/chapters/chapter2/Code/Descriptive/Figures/"
rsync_clean "$CHAPTER2_SRC/Code/Descriptive/Tables/" "$ROOT_DIR/chapters/chapter2/Code/Descriptive/Tables/"
rsync_clean "$CHAPTER2_SRC/Code/Regressions/Other/" "$ROOT_DIR/chapters/chapter2/Code/Regressions/Other/"

find "$ROOT_DIR/chapters/chapter1/Subfiles" -name '*.tex' -print0 | \
  xargs -0 perl -0pi -e 's/\{Tables\//\{\.\.\/Tables\//g'

perl -0pi -e 's/\\label\{sec:intro\}/\\label{sec:chapter1-intro}/g' \
  "$ROOT_DIR/chapters/chapter1/Subfiles/intro.tex"

perl -0pi -e 's/\\label\{sec:results\}/\\label{sec:chapter1-results}/g' \
  "$ROOT_DIR/chapters/chapter1/Subfiles/results.tex"

perl -0pi -e 's/Appendix~\\ref\{sec:appendix\}/Appendix~\\ref{app:chapter2}/g' \
  "$ROOT_DIR/chapters/chapter2/Paper/Subfiles/introduction.tex"

perl -0pi -e 's/\\label\{sec:intro\}/\\label{sec:chapter2-intro}/g' \
  "$ROOT_DIR/chapters/chapter2/Paper/Subfiles/introduction.tex"

perl -0pi -e 's/\\ref\{sec:results\}/\\ref{sec:chapter2-results}/g' \
  "$ROOT_DIR/chapters/chapter2/Paper/Subfiles/introduction.tex"

perl -0pi -e 's/\\label\{sec:results\}/\\label{sec:chapter2-results}/g' \
  "$ROOT_DIR/chapters/chapter2/Paper/Subfiles/results.tex"

perl -0pi -e 's@\\inputtable\{\.\./\.\./Code/Regressions/Other/returns_portfolio_moments_pooled\.tex\}@\\input{../../Code/Regressions/Other/returns_portfolio_moments_pooled.tex}@g' \
  "$ROOT_DIR/chapters/chapter2/Paper/Subfiles/data.tex"

find "$ROOT_DIR/chapters/chapter3/Subfiles" -name '*.tex' -print0 | \
  xargs -0 perl -0pi -e 's/^\\documentclass\[Chp3\.tex\]\{subfiles\}/\\documentclass[..\/..\/..\/00-main.tex]{subfiles}/'

perl -0pi -e 's/\\label\{sec:Conclusion\}/\\label{sec:chapter3-conclusion}/g' \
  "$ROOT_DIR/chapters/chapter3/Subfiles/Conclusion-decory.tex"

perl -0pi -e 's/\\ref\{sec:Conclusion\}/\\ref{sec:chapter3-conclusion}/g' \
  "$ROOT_DIR/chapters/chapter3/Subfiles/Intro-decory.tex"

perl -0pi -e 's/\\addcontentsline\{toc\}\{section\}\{Appendices\}\s*%[^\n]*\n\s*\\hypertarget\{Appendices\}\{\}\s*%[^\n]*\n\s*\\section\{Proofs\}/\\section{Proofs}/s' \
  "$ROOT_DIR/chapters/chapter3/Subfiles/Appendix-decory.tex"

merge_bib_files "$CHAPTER1_SRC/Chp1.bib" "$CHAPTER2_SRC/Paper/Chp2.bib" "$CHAPTER3_SRC/References.bib" > "$ROOT_DIR/thesis.bib"

echo "Imported chapter sources into $ROOT_DIR/chapters"
